export const PostActionTypes = {
GET_POSTS: 'GET_POSTS',
GET_POST: 'GET_POST',
POST_ERROR: 'POST_ERROR',
LIKE_POST: 'LIKE_POST',
DISLIKE_POST: 'DISLIKE_POST',
DELETE_POST: 'DELETE_POST',
ADD_POST: 'ADD_POST'
}