export const ProfileActionTypes = {
GET_PROFILE: 'GET_PROFILE',
GET_PROFILES: 'GET_PROFILES',
GET_REPOS: 'GET_REPOS',
UPDATE_PROFILE: 'UPDATE_PROFILE',
CLEAR_PROFILE: 'CLEAR_PROFILE',
PROFILE_ERROR: 'PROFILE_ERROR',
ACCOUNT_DELETED: 'ACCOUNT_DELETED',
}