export const UserActionTypes = {
REGISTER_SUCCESS: 'REGISTER_SUCCESS',
REGISTER_FAIL: 'REGISTER_FAIL',
USER_LOADED: 'USER_LOADED',
AUTH_ERROR: 'AUTH_ERROR',
LOGIN_SUCCESS: 'LOGIN_SUCCESS',
LOGIN_FAIL: 'LOGIN_FAIL',
LOGOUT: 'LOGOUT',
ACCOUNT_DELETED: "ACCOUNT_DELETED",
USER_IMAGE_UPDATED: "USER_IMAGE_UPDATED",
USER_ERROR: "USER_ERROR"
}